In [12]:
import numpy as np

# -----------------------------------
# Input Sequence
# -----------------------------------
# Example: 3 tokens with embedding size 4

X = np.array([
    [1, 0, 1, 0],
    [0, 2, 0, 2],
    [1, 1, 1, 1]
])

print("Input Matrix:\n")
print(X)

# -----------------------------------
# Initialize Weight Matrices
# -----------------------------------

np.random.seed(42)

W_Q = np.random.rand(4, 4)

W_K = np.random.rand(4, 4)

W_V = np.random.rand(4, 4)

# -----------------------------------
# Compute Queries, Keys, Values
# -----------------------------------

Q = np.dot(X, W_Q)

K = np.dot(X, W_K)

V = np.dot(X, W_V)

print("\nQuery Matrix:\n")
print(Q)

print("\nKey Matrix:\n")
print(K)

print("\nValue Matrix:\n")
print(V)

# -----------------------------------
# Attention Scores
# -----------------------------------

d_k = K.shape[-1]

scores = np.dot(Q, K.T) / np.sqrt(d_k)

print("\nAttention Scores:\n")
print(scores)

# -----------------------------------
# Softmax Function
# -----------------------------------

def softmax(x):

    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))

    return exp_x / np.sum(
        exp_x,
        axis=-1,
        keepdims=True
    )

attention_weights = softmax(scores)

print("\nAttention Weights:\n")
print(attention_weights)

# -----------------------------------
# Final Attention Output
# -----------------------------------

output = np.dot(attention_weights, V)

print("\nSelf-Attention Output:\n")
print(output)

Input Matrix:

[[1 0 1 0]
 [0 2 0 2]
 [1 1 1 1]]

Query Matrix:

[[0.97565513 1.65878688 0.75257844 1.56856834]
 [1.97692256 0.73666726 0.47981716 2.09916131]
 [1.96411641 2.02712052 0.99248702 2.61814899]]

Key Matrix:

[[0.76031223 1.30993239 0.6316188  0.80546358]
 [2.40853493 0.37188855 1.799379   1.07377193]
 [1.96457969 1.49587667 1.5313083  1.34234955]]

Value Matrix:

[[0.18708983 1.44406245 1.00002055 1.71771775]
 [1.1267875  1.5203888  1.99188821 1.92044103]
 [0.75048358 2.20425685 1.99596466 2.67793827]]

Attention Scores:

[[2.32673428 3.0026209  3.82804472]
 [2.23096111 4.07641929 4.26917076]
 [3.44221483 5.04083054 5.9626301 ]]

Attention Weights:

[[0.13416802 0.26374415 0.60208783]
 [0.06663179 0.42184582 0.51152239]
 [0.05440714 0.26910756 0.6764853 ]]

Self-Attention Output:

[[0.77414211 1.92189687 1.86126567 2.34932192]
 [0.87168588 1.86511686 1.92788349 2.29441001]
 [0.82109717 1.97886278 1.94068118 2.42184718]]
